### ISSUE TITLE
Home Assistant 2024.7.0 - wiim_custom - unexpected keyword argument

### ISSUE THREAD

**Issue by GitIt-GotIt** [onlyoneme/home-assistant-custom-components-wiim#22]
Anyone else get this after updating HomeAssistant to 2024.7.0?  I am running the beta wiim_custom buile (2024.5.0 async setup)
Thanks

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:364
integration: Media player (documentation, issues)
First occurred: 1:12:19 PM (1 occurrences)
Last logged: 1:12:19 PM

Error while setting up wiim_custom platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/wiim_custom/media_player.py", line 206, in async_setup_platform
    wiim = WiiMDevice(name,
          ^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim_custom/media_player.py", line 230, in __init__
    self._factory = UpnpFactory(requester, disable_unknown_out_argument_error=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UpnpFactory.__init__() got an unexpected keyword argument 'disable_unknown_out_argument_error'

**Comment by jiruss** [comment]
Yes. I am getting it as well. I was trying the beta to fix issue #19 and now I am getting this.

**Comment by JasonOggy** [comment]
Mee to. So is LINKPLAY https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues/145

**Comment by GitIt-GotIt** [comment]
Good find.  Comment out line 230 in media_player.py duplicate it leaving out ", disable_unknown_out_argument_error=True" and restart home assistant. Component then starts. I did get an xml parse error in the home-assistant.log, but when i ran the WIIM app directly it was angry too. i restarted the WIIM and things seem back to normal now

`        self._factory = UpnpFactory(requester)`
![image](https://github.com/onlyoneme/home-assistant-custom-components-wiim/assets/123896689/71520542-d171-4fcc-8be4-bec600fa41fe)

**Comment by fredR142** [comment]
Thanks  , fixed mine too !
